### ISSUE TITLE
Manager component uses confusing abstractions between sender and receiver

### ISSUE THREAD

**Issue by pablothedolphin** [speckleworks/SpeckleUnity#18]
Refactor the four classes so that only a single component is in the scen and it contains n number of client objects that can be configured through the inspector for easier to understand use.

**Comment by cwmorse** [comment]
How would this work if I want to treat different received streams in different ways? In my workflow it seemed easier to have separate components for each stream.

**Comment by pablothedolphin** [comment]
The minimum dependancies for each stream are that they need a stream ID. So I wanted to refactor the manager component to act as a wrapper to a list of speckle models (or some better name for this non monobehaviour) which had an API like "Client.AddStream (string streamID)" which would add a new root transform underneath the manager game object for the new stream. This API would have overloads for if the geometry needed a sender or receiver or both which replaces the need for prefabs or empty transforms with just a component on them. 

This approach removes the need to constantly use the "FindGameObjects" method which iterates over even UI objects and meshes which in turn kills performance. This one new mono behaviour in the scene will already have awareness of all streams because it is the gatekeeper to creating them. 

Also, when developers want to add and remove streams during runtime, they'll need to create some collection of them they can maintain anyway. Providing a single mono behaviour which provides this collection out of the box is an added convenience so devs don't need to instanciate prefabs and add and remove stuff themselves. I can also add a this[] field to allow devs to access each stream object by index or streamID. 

It also simplifies the end user API which will only require knowledge of one class rather than 4 (including the custom unity event) at a minimum. 

Finally, because methods are being made virtual or abstract, devs can override functionality where they see fit to change or extend behaviour. 

Does all of that sound right to you?

**Comment by cwmorse** [comment]
Just my two cents.... I don't really have any experience developing apis for others to use, so take it for what it's worth, which certainly may be not much :)

Depending on how things are split up, I might argue that 3 smaller classes that separate functionality can be easier to understand than one large class. FindGameObjects is only being used once on start, so I'm not too worried about the performance hit there. Creating a new root under the manager for each stream doesn't seem inherently better to me than a separate transform with a component on it (and some people online suggest that performance is better with separate hierarchies than everything under one single gameobject). You can still provide convenience collections and api calls while keeping clients as separate components.

I also go back to customizing stream behavior. I have times where I set up streams ahead of time in the editor, and apply different functionality on top of them. For example one stream for 'background' mesh geometry that doesn't change, one stream for point that are used to procedurally drive something, one stream of dynamic geometry from grasshopper. To me it makes more sense to have three separate gameobjects that I can then add different scripts to at design time, and feels more like grasshopper where each sender or receiver is a different thing.

**Comment by pablothedolphin** [comment]
I see so the way the plugin has been used so far is what lead to the current design that makes sense. I've come at this from a biased perspective of what my team is wanting to do with Speckle which is to develop some standalone software which allows users to log in and select which stream they wish to view and switch between streams during run time rather than design time. Kind of like what the web viewer offers now.

I guess the best approach would be a middle ground that offers a similar level of flexibility for designers making something bespoke but also something that offers clean APIs for use cases like I described in creating larger pieces of software. I'll hold off on this issue for now and, if you're happy to, get your thoughts on the design I come up with once I have something working before merging the development.
