### ISSUE TITLE
Including Unity in type names is redundant

### ISSUE THREAD

**Issue by pablothedolphin** [speckleworks/SpeckleUnity#19]
The whole API is for unity so there's no need to include it everywhere. Will also shorten class names and make code more readable.

**Comment by cwmorse** [comment]
I kind of thought so too, but it seemed to be how other clients were naming things and tried to be consistent? Maybe I went overboard :)

**Comment by pablothedolphin** [comment]
Ah if there's a convention already in place then it's probably best to keep it as is. I'll check out one of the other clients just so I can see for myself but Tha ks for the heads up!
