### ISSUE TITLE
Speckle Kits need to be installed for the code to run

### ISSUE THREAD

**Issue by pablothedolphin** [speckleworks/SpeckleUnity#32]
This is due to how the SpeckleCore DLL was coded. Ideally this could be changed and merged into the main SpeckleCore repo as a pull request.

**Comment by Dean-RGB** [comment]
do we figure this is what is causing Android build issues?

**Comment by pablothedolphin** [comment]
no it looks like its the web socket stuff causing the issue (the bit that makes syncing with changes work) so either that gets fixed or we make it so that somehow on android it doesn't run that code in speckle core. so for now, android won't be supported yet but it definitely can be!

**Comment by pablothedolphin** [comment]
Either way, the kits are no longer needed. You can check the branch i made on speckle core to see what i did to it. I basically did what we talked about
